# Generated by Django 4.2.4 on 2024-05-30 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('adminName', models.TextField()),
                ('adminEmail', models.EmailField(max_length=254)),
                ('adminNo', models.CharField(max_length=12)),
                ('adminPassword', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='studentClass',
            fields=[
                ('classID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('className', models.TextField()),
                ('maxCapacity', models.IntegerField()),
                ('currentCapacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('teacherName', models.TextField()),
                ('teacherEmail', models.EmailField(max_length=254)),
                ('teacherNo', models.CharField(max_length=12)),
                ('teacherPassword', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('studName', models.TextField()),
                ('studEmail', models.EmailField(max_length=254)),
                ('phoneNo', models.CharField(max_length=12)),
                ('dateOfBirth', models.TextField()),
                ('gender', models.TextField()),
                ('address', models.TextField()),
                ('parentsName', models.TextField()),
                ('parentsNo', models.CharField(max_length=12)),
                ('studPassword', models.TextField()),
                ('classID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='StudentRegistrationManagementSystem.studentclass')),
            ],
        ),
    ]
