# Generated by Django 4.2.4 on 2024-06-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentRegistrationManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phoneNo',
            new_name='studNo',
        ),
    ]
